### ISSUE TITLE
 have trouble running the train

### ISSUE THREAD

**Issue by Von-06** [afnan29alofi/Pedestrian-Intent-Prediction#2]
Hi, thanks for your contribution.I am having trouble running train_test.py.

Traceback (most recent call last):
  File "train_test.py", line 12, in <module>
    from action_predict import action_prediction
  File "Pedestrian-Intent-Prediction-main/action_predict.py", line 8, in <module>
    from MultiHeadAttentionClass import MultiHeadedAttention
ModuleNotFoundError: No module named 'MultiHeadAttentionClass'

So what can i do?

**Comment by duquancheng** [comment]
I have the same problem, have you solved it?

**Comment by duquancheng** [comment]
> Hi, thanks for your contribution.I am having trouble running train_test.py.
> 
> Traceback (most recent call last): File "train_test.py", line 12, in from action_predict import action_prediction File "Pedestrian-Intent-Prediction-main/action_predict.py", line 8, in from MultiHeadAttentionClass import MultiHeadedAttention ModuleNotFoundError: No module named 'MultiHeadAttentionClass'
> 
> So what can i do?

I have the same problem, have you solved it?

**Comment by afnan29alofi** [comment]
when run train  use:
python train_test.py -c config_files/Ours/PPCI_att_Jaad.yaml
or 
python train_test.py -c config_files_pie/Ours/PPCI_att.yaml

**Comment by Von-06** [comment]
> when run train use: python train_test.py -c config_files/Ours/PPCI_att_Jaad.yaml or python train_test.py -c config_files_pie/Ours/PPCI_att.yaml

I still have problems.Could you tell me what version of tensorflow you use?
I use tensorflow-gpu 2.2.0 ,cuda10.1 and cudnn 7.6.5
